<?php

namespace App\Enums;

class AmoEnum
{
    const LEAD_PRODUCT_NAME_FIELD_ID = 465113;
    const CONTACT_DATE_OF_BIRTH_FIELD_ID = 626367;
    const CONTACT_GENDER_FIELD_ID = 626533;

    const PRODUCT_CATALOG_ID = 7527;
    const PRODUCT_CATALOG_PRICE_FIELD_ID = 938161;

    const PHONE_CUSTOM_FIELD_CODE = 'PHONE';
    const EMAIL_CUSTOM_FIELD_CODE = 'EMAIL';
    const WORK_CUSTOM_FIELD_VALUE_CODE = 'WORK';
}
